version: '3.8'
services:
  gamingapi_website:
    build: ./
    image: ghcr.io/gamingapi/website:main
    ports:
      - 3000
    restart: unless-stopped
    environment:
      AUTH_GITHUB_ID: "${AUTH_GITHUB_ID}"
      AUTH_GITHUB_SECRET: "${AUTH_GITHUB_SECRET}"
      NEXTAUTH_SECRET: "${NEXTAUTH_SECRET}"
      NEXTAUTH_URL: "${NEXTAUTH_URL}"
    deploy:
      replicas: 1
      update_config:
        delay: 5m
        parallelism: 1
        failure_action: rollback
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.labels.service == true]
    networks:
      - eventstack
networks:
  eventstack:
    external: true
